language: python
python:
  - "3.5"
install:
  - nvm install 0.12
  - node --version
  - npm --version
  - nvm --version
  - npm install
script:
  - npm build
  - npm test
after_success:
  - cat ./coverage/lcov.info | ./node_modules/.bin/coveralls
