language: node_js
sudo: required
dist: trusty
node_js:
  - "0.11"
  - "0.10"
before_install:
 - sudo rm -f /usr/bin/python3
 - sudo ln -s $(which python3.5) /usr/bin/python3
 - python3 -V
script:
 - npm build
 - npm test
after_success:
 - cat ./coverage/lcov.info | ./node_modules/.bin/coveralls
