language: node_js
sudo: required
dist: trusty
node_js:
  - "0.12"
before_install:
 - sudo rm -f /usr/bin/python3
 - sudo ln -s $(which python3.5) /usr/bin/python3
 - sudo pip3.5 install -r requirements.txt
 - python3 -V
script:
 - npm build
 - npm test
after_success:
 - cat ./coverage/lcov.info | ./node_modules/.bin/coveralls
